### ISSUE TITLE
Android 커리큘럼 작성시 참고해주세요

### ISSUE THREAD

**Issue by SeungYongSon** [ilovedsm/dsm-curriculum#1]
https://github.com/mobile-roadmap/android-developer-roadmap

안드 개발자 로드맵입니다.   
이 로드맵을 토대로 커리큘럼을 짜면 도움이 되지 않을까 싶습니다.

**Comment by DonggeunYu** [comment]
의견 감사합니다. 참고해서 좋은 커리큘럼을 만들도록 하겠습니다!

진행 상황을 말씀드리자면 현재는 서버만 작성중이고 서버가 완성되면 다른 분야의 커리큘럼 작성을 위한 기획을 할 예정입니다. 그 후에 기획을 바탕으로 다른 분야도 작성될 예정입니다.
