### ISSUE TITLE
학교의 학생들을 위한 방향

### ISSUE THREAD

**Issue by 20chan** [ilovedsm/dsm-curriculum#7]
질적으로나 양적으로나 [이런 로드맵](https://github.com/kamranahmedse/developer-roadmap) 이 훨씬 나은데 굳이 이런 문서를 만든데에는 차별점이 필요한 것 같습니다.

이 학교에서 왜 이런 공부를 해야하는지 혹은 학교에서 도움을 받을 수 있는 방법 등의 구체적인 내용이 학교의 학생들이 별다른 사전지식 없이 쉽게 이해하고 도움받을 수 있는 방법에 초점을 맞추는게 좋지 않을까요?

또한 학교에서 학생은 프로그래밍이라는 분야에서도 수많은 길을 선택할 수 있고 또 그 밖으로도 방법이 매우 많고 그 방법들을 모두 존중해줬으면 좋겠습니다. 단순히 *내가 공부했는데 너희는 뭐하니* 정도의 생각으로 남을 비방하는 어투는 피해줬으면 합니다.

프로그래밍 경험이 오래 있는 학생이든 아니든, 많은 도움을 받아 누구에게든 실질적으로 도움이 되고 학교에서의 3년을 잘 설계할 수 있도록 도와주는 문서가 되기를 바랍니다.
감사합니다.

**Comment by DonggeunYu** [comment]
먼저 관심을 가져주셔서 감사합니다.

커리큘럼의 목적 즉 타겟은 학생의 전체가 아닌 전공 동아리, 인맥 적으로 정보를 얻기 힘들어하는 친구들을 위해 작성하는 것입니다. 그래서 최대한 키워드 형태로 작성하였습니다. 스스로 공부할 방향성을 찾을 수 있도록.

frontend, backend 등 다양한 분야에 대해 커리큘럼은 이미 있습니다. 그러나 학교 학생들 스스로 커리큘럼을 작성하는 것 자체가 의미 있다고 생각합니다. 언제든지 학생들 스스로 쉽게 튜닝할 수 있었으면 좋겠습니다.

"또한 학교에서 학생은 프로그래밍이라는 분야에서도 수많은 길을 선택할 수 있고 또 그 밖으로도 방법이 매우 많고 그 방법들을 모두 존중해줬으면 좋겠습니다. 단순히 내가 공부했는데 너희는 뭐하니 정도의 생각으로 남을 비방하는 어투는 피해줬으면 합니다."
이 부분에서는 제가 잘 이해했다면 아마 '방향성'에서 이런 생각이 드셨을 수도 있습니다. 예를 들어 설명해드리자면 이 학교에 와서 프로그래밍을 처음 접하고도 단순히 어려워서 C, JAVA가 좋지 않다고 하면서 Python만을 고집하는 사례도 있고 특히 서버는 Python으로 몰리는 현상이 심합니다. 저도 IT분야에 대해 잘 알지는 못하지만 개인적으로는 이런 현상은 좋지 못하여 강력히 어필하고 싶었습니다.

사실 현재 15~20명(3학년 선배 4명을 제외하고 2학년은 개인적으로 따로 부탁드렸습니다.) 재학생분들이 문서를 작성을 해주셨지만, 많이 부족합니다. 이를 채우기 위해서 부탁을 드려도 개인 공부나 취업 준비로 인해 꺼리는 분들이 많습니다. "나만 잘 해서 취업하자"라는 생각을 보통 많이 하고 있기 때문에 문서 작성에 어려움이 많습니다. 어쩌면 그게 옳을 수도 있는거고요.

최근, 커리큘럼 작성에 대해 방향성을 찾지 못하고 있습니다. 그래서 이제는 재학생이 아닌 졸업생분께 부탁드리면 좋지 않을까라는 생각을 하고 있습니다. 실례가 안 되신다면 졸업생으로 DMS 커리큘럼 작성에 함께해주셨으면 좋겠습니다.

마지막으로 긴 글 읽어주셔서 감사합니다.

**Comment by 20chan** [comment]
>frontend, backend 등 다양한 분야에 대해 커리큘럼은 이미 있습니다. 그러나 학교 학생들 스스로 커리큘럼을 작성하는 것 자체가 의미 있다고 생각합니다. 언제든지 학생들 스스로 쉽게 튜닝할 수 있었으면 좋겠습니다.

이러한 일의 의의를 모르겠습니다. 많은 개발자가 인정하고 훨씬 실력 좋은 개발자의 로드맵이 있는데 학생들이 스스로 커리큘럼을 작성하는게 의미가 있다는 거면 그걸 굳이 공개 리포로 다른 학생들에게 보라고 하는건 좋은 선택이 아니지 아니지 않을까요? 잘못되거나 의견이 다른 사람이 학생이 작성한 커리큘럼을 봐서 혼란이 온다면 좋지 않다고 생각합니다.
글을 작성하는 학생이 발전함을 원하는 거라면 개인 블로그 등에 작성하는게 맞는거 같습니다.

>프로그래밍을 처음 접하고도 단순히 어려워서 C, JAVA가 좋지 않다고 하면서 Python만을 고집하는 사례도 있고 특히 서버는 Python으로 몰리는 현상이 심합니다.

학교와 같은 작은 공동체에서 기술 물타기나 의미없는 기술 저울질이 굉장히 심하다는건 알고 있습니다. 그래서 더욱 이런 학생이 작성하는 리포에서 중립성을 가지기는 어렵습니다. 여기서 커리큘럼의 방향성 등을 학생이 생각하여 작성하여 알리는건 물타기나 기술 저울질이 심해지는 것으로밖에 보이지 않습니다.

자그마한 충고부터 이러한 커리큘럼 혹은 로드맵같은 조언같은 글은 말의 무게가 굉장히 큽니다. 남에게 어떤 길이 좋고 나쁘고에 대해 말하는 것은 그 사람이 어떻게 받아드리냐 와 별개로 책임감이 큰 행동이며 쉽게 작성하고 배포해도 되는 일이 아니라고 생각합니다.

리포의 취지는 충분히 공감이 되고 그러므로 더욱 기술적인 부분은 인정받은 멋진 개발자가 쓴 글을 가져오거나 검증을 받는 등 개선의 요지가 필요한 것 같습니다.

**Comment by DonggeunYu** [comment]
## 왜 만들어야 하지?
'의미'라는 것을 글로 표현하기가 힘든 것 같네요.
제가 1학년 때 딥러닝 분야를 공부하고 싶었습니다. 그러나 검색을 해보면 너무 어렵고 어떻게 방향을 잡아야할지 몰랐었습니다. 어느 과정으로 공부해야 고등학교라는 짧은 3년동안 알차게 공부해서 취업할 수 있을지를 몰랐습니다. 1학년 1학기 때 운 좋게도 딥러닝 전공 동아리를 들어가게 되어서 선배로부터 방향성을 알게되었고 재밌게 공부할 수 있었습니다. 그러나 운이 부족해서 아쉽게 동아리에 들어가지 못한 친구들 중에는 스스로 잘 한 친구도 있었지만 방향성을 잡지 못한 친구들도 꽤 있었습니다. 이런 친구들에게 이 커리큘럼을 만들어주고 싶었습니다.

다음 글은 심리적인 부분이기 때문에 크게 와닿지 않으실 수도 있습니다.
대마고 학생들의 아쉬운점은 자존감 즉 학교에 대한 자신감이 부족한 것 같습니다. 만약 1학년에 들어와서 선배가 작성한 커리큘럼을 보게 된다면 저는 매우 고맙게 느끼고 다음 학년이 되면 나도 1학년을 위해 노력해야겠다는 생각이 들 것 같습니다.

튜닝
고등학교 3년(2~2.5년)이라는 짧은 기간동안 배우고 취업을 해야하기 때문에 다양한 로드맵을 따라하는 것은 좋은 시도 일 수도 있지만 같은 고등학교에서 같은 시간 동안 배우고 취업하신 선배분들의 로드맵이 더 효율적이라고 생각하였습니다.

## '혼란'에 대한 답변
'꼭 읽어야 하는 글!' 글에 나와있듯이 충분히 그런 문제를 고려하고 있습니다. 단순히 참고 자료로 이용하는 것을 추천하고 있습니다. 모든 방향에서 비관적으로 생각하고 고려중이며 issue를 열어주신 20chan께도 감사드립니다.

## "학교와 같은 ~ 보이지 않습니다."에 대한 답변
이 부분도 충분히 고려하고 있습니다. backend 커리큘럼을 보면 특정 언어로 커리큘럼이 구성된 것이 아닌 기술 즉 키워드 형태로만 제공하고 있습니다. 커리큘럼에는 최대한 언어에 대한 내용을 배제할 계획입니다.

## "자그마한 ~ 생각합니다.", "리포의 ~ 같습니다"에 대한 답변
현재 README.md나 어떠한 커리큘럼에 문제가 있다고 생각되시면 issue를 통해 문제를 제기해주셨으면 좋겠습니다.

현재 다수의 관리자는 2학년이며 3학년이 되면 2학년 학생들에게 물려줄 예정입니다. 책임감을 가질 수 있는 다수의 학생들에게 물려줄 것입니다.
큰 issue에 대해서는 10명이 넘는 다수가 함께 검증 할 것이고 GitHub의 자유로운 오픈소스 커뮤니티 문화를 지향하고 있습니다.
