### ISSUE TITLE
Git 관련 내용도 추가해주세요

### ISSUE THREAD

**Issue by SayBGM** [ilovedsm/dsm-curriculum#8]
좋은 프로젝트인거같은데 Git 제대로 쓰지 못하는 학생들이 꽤나 많은 것 같아요.

개발자 필수 조건이기도 한 Git 관련 문서 추가하면 더할 나위없이 좋을거같아요.

**Comment by DonggeunYu** [comment]
다양한 분야의 커리큘럼을 제공하고 싶습니다.
커리큘럼은 오픈소스이기 때문에 누구나 작성 가능합니다.
괜찮으시다면 작성해주실 수 있을까요?

**Comment by SayBGM** [comment]
시간 나면 작성해볼게요
